language: c
sudo: false
dist: trusty

compiler:
- gcc
- clang

os:
- linux

env:
  global:
  - LIBTOOL_SUPPRESS_DEFAULT=no
  - UPLOAD_DIR=_4upload
  - TEST_NOOK="$UPLOAD_DIR/$TRAVIS_JOB_NUMBER-$TRAVIS_EVENT_TYPE-$TRAVIS_BRANCH$TRAVIS_TAG$TRAVIS_PULL_REQUEST_SLUG"
  - EXTRA_CFLAGS="-Wall -Werror -ggdb3 -gdwarf-4"
  - SLAPD_TESTING_TIMEOUT=555

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - uuid-dev
    - libelf-dev
    - krb5-multidev
    - heimdal-multidev
    - libcrack2-dev
    - libsasl2-dev
    - libperl-dev
    - libtool
    - libltdl-dev
    - binutils-dev
    - libssl-dev
    - libgnutls-dev
    - libwrap0-dev
    - unixodbc-dev
    - libslp-dev
    - libdb-dev
    - gdb
#   - libwiredtiger-dev

before_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_1572229a40f3_key -iv $encrypted_1572229a40f3_iv
    -in build/ci/upload_rsa.enc -out ~/.ssh/id_rsa -d && chmod 600 ~/.ssh/id_rsa;
  fi
- mkdir -p $TEST_NOOK

script:
- ./bootstrap.sh --dont-cleanup || cp build/*.rej build/*.orig $TEST_NOOK/
  && ./configure CFLAGS=-Ofast --prefix=$HOME/_install --enable-check=always
  --enable-hipagut=always --enable-debug --disable-syslog --enable-overlays
  --enable-maintainer-mode --enable-dynacl --enable-aci --enable-crypt --enable-lmpasswd
  --enable-spasswd --enable-slapi --enable-rlookups --enable-slp --enable-wrappers
  --enable-backends --disable-bdb --disable-hdb --disable-ndb --disable-modules
  --enable-ci
- make --keep-going && make --keep-going install
  && ulimit -c unlimited && make test </dev/null
- make --keep-going dist
  && mkdir _dist && (cd _dist && tar -xaf ../*.tar.* --strip=1
  && ./configure CFLAGS=-Os --prefix=$HOME/_dist/_install
  --enable-overlays=mod --enable-contrib --enable-experimental
  --enable-debug --enable-dynacl --enable-aci --enable-crypt --enable-lmpasswd --enable-spasswd
  --enable-slapi --enable-rlookups --enable-slp --enable-wrappers --enable-backends=mod
  --disable-ndb --disable-dependency-tracking --disable-wt
  && make --keep-going && make --keep-going install)

after_failure:
- test -n "$(ls -A tests/testrun)" && tar caf $TEST_NOOK/testrun.tar.gz -C tests/testrun .
- scp -o StrictHostKeyChecking=no -B -P $UPLOAD_PORT -rp $UPLOAD_DIR/* $UPLOAD_USER@$UPLOAD_HOST:~/$TRAVIS_REPO_SLUG/ 2>&1 | sed -n 's/^.*: \([^:]\+$\)/\1/p'
